---
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    command: sh -c "go run main.go"
    volumes:
      - ./app:/go
    depends_on:
      - db
    ports:
      - "8081:8081"
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - app
  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=routine
    volumes:
      - db-data:/var/lib/postgresql/data
  front:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    ports:
      - "3009:3000"
    command: sh -c "yarn start"
volumes:
  db-data:
